[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "GenerateRandomSolidSolution"
version = "2023.0"
description = "A Python script modifier for OVITO to generate random solid solutions in whole or selected subregions of a sample."
authors = [{name = "Daniel Utt", email = "utt@ovito.org"}]
maintainers = [{name = "Daniel Utt", email = "utt@ovito.org"}]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
repository = "https://github.com/nnn911/generate-random-solid-solution"

[project.entry-points.'OVITO.Modifier']
GenerateRandomSolidSolution = "GenerateRandomSolidSolution:GenerateRandomSolidSolution"

[tool.setuptools.packages.find]
where = ["src"]