[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Generate Random Solid Solution"
version = "2023.0"
description = "OVITO Python script modifier to chang the particle type values to create a random solid solution of a given composition."
keywords = ["ovito", "python-script-modifier"]
authors = [{name = "Daniel Utt", email = "utt@ovito.org"}]
maintainers = [{name = "Daniel Utt", email = "utt@ovito.org"}]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
repository = "https://github.com/nnn911/generate-random-solid-solution"

[project.entry-points.'OVITO.Modifier']
"Generate Random Solid Solution" = "GenerateRandomSolidSolution:GenerateRandomSolidSolution"

[tool.setuptools.packages.find]
where = ["src"]